name: Python Package using Conda

on: 
  pull_request:
    branches: [master, main]
    types: [synchronize, opened, reopened, ready_for_review]

jobs:
  build-and-test:
    name: Test on (${{ matrix.os }}-Python${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.10", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Which python
        run: |
          python --version
      - name: Install dependencies
        run: |
          pip install .[templates,test]
          pip install "zarr<3.0.0"
      - name: pip list
        run: |
          pip list
      - name: Test with pytest and build coverage report
        run: |
          pytest -s
